server:
  port: 9000

#logging:
#  level:
#    root: DEBUG

spring:
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms-quiz
    username: postgres
    password: sadiq4852
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

web-q5:
  app:
    secret-key: salamat
    expiration-ms: 86400000
